Update THORIUM-PORTABLE

diff --git a/portable/THORIUM-PORTABLE b/portable/THORIUM-PORTABLE
--- a/portable/THORIUM-PORTABLE
+++ b/portable/THORIUM-PORTABLE
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (c) 2022 The Chromium Authors and Alex313031. All rights reserved.
+# Copyright (c) 2023 The Chromium Authors and Alex313031. All rights reserved.
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
@@ -8,6 +8,22 @@
 export CHROME_WRAPPER="`readlink -f "$0"`"
 
 HERE="`dirname "$CHROME_WRAPPER"`"
+
+# We include some xdg utilities next to the binary, and we want to prefer them
+# over the system versions when we know the system versions are very old. We
+# detect whether the system xdg utilities are sufficiently new to be likely to
+# work for us by looking for xdg-settings. If we find it, we leave $PATH alone,
+# so that the system xdg utilities (including any distro patches) will be used.
+if ! which xdg-settings &> /dev/null; then
+  # Old xdg utilities. Prepend $HERE to $PATH to use ours instead.
+  export PATH="$HERE:$PATH"
+else
+  # Use system xdg utilities. But first create mimeapps.list if it doesn't
+  # exist; some systems have bugs in xdg-mime that make it fail without it.
+  xdg_app_dir="${XDG_DATA_HOME:-$HOME/.local/share/applications}"
+  mkdir -p "$xdg_app_dir"
+  [ -f "$xdg_app_dir/mimeapps.list" ] || touch "$xdg_app_dir/mimeapps.list"
+fi
 
 # Always use our versions of ffmpeg libs.
 # This also makes RPMs find the compatibly-named library symlinks.
@@ -44,4 +60,4 @@ exec > >(exec cat)
 exec 2> >(exec cat >&2)
 
 # Note: exec -a below is a bashism.
-exec -a "$0" "$HERE/thorium" --user-data-dir=$(pwd)/.config/thorium --no-default-browser-check --enable-experimental-web-platform-features --new-canvas-2d-api "$@"
+exec -a "$0" "$HERE/thorium" "--user-data-dir=$(pwd)/.config/thorium" "--no-default-browser-check" "--enable-experimental-web-platform-features" "--new-canvas-2d-api" "$@"
